version: "3.9"

services:
  server:
    restart: always
    build:
      context: server
      args: 
        VERSION: latest
    ports:
      - 8080:8080
    networks:
      - chatApp
  client:
    restart: always
    depends_on: 
      - server
    build:
      context: client
      args:
        VERSION: latest
    ports:
      - 80:80
    networks:
      - chatApp

networks:
  chatApp:
    name: chat-app
    