
on:
  push:
    branches:
      - main
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    name: Publish docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: recursive
      - name: Build Docker images
        run: docker-compose up -d 
      - name: publish
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          version: 'v0.1'
          docker_compose: 'docker-compose.yml'
          repo_token: "${{ secrets.GITHUB_TOKEN }}"