on:
  # Allows to run by API call
  workflow_dispatch:

jobs:
  sync:
    name: 'Update submodules'
    runs-on: ubuntu-latest

    # Switch to bash shell
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.CI_TOKEN }}
        submodules: true

    # Update references
    - name: Update submodules
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Commit update
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"

